#string methods
print ("=")
print ("hello".count("e"))
print ("=")
text = "happy birthday"
print (text.count("a"))
print ("=")
print (text.count("day"))
print ("=")
x = "Happy Birthday!"
print ("=")
print (x.lower())
print (x.upper())
print ("=")
x = x.upper()
print ("should be all in upper case: -->",x)
print ("=")
x = x.lower()
x = x.capitalize()
print ("should be all in lower case: -->",x)
print ("=")
x = x.title()
print ("every letter of every word should be capitalized",x)
print ("=")
print ("is the word all in lower case?: -->",x.islower())
print ("is the word all in upper case?: -->",x.isupper())
print ("is every letter of every word in upper case?: -->",x.istitle())
print ("is it alpha? (has no space?): -->",x.isalpha())
print ("is it digit?: -->",x.isdigit())
print ("is the word all in upper case?: -->",x.isupper())
print ("is it alpha numeric?: -->",x.isalnum())
print ("=")
